# theme = "monokai_pro"
# theme = "sonokai_atlantis"
theme = "onedark"

[editor]
cursorline = true
auto-save = true
true-color = true
bufferline = "multiple"
color-modes = true
# auto-info = false
auto-completion = false

[editor.soft-wrap]
enable = true

#[editor.whitespace.render]
#tab = "all"
#space = "all"
#newline = "all"

# [editor.indent-guides]
# render = true
# character = "â”Š"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false